enum TokenType
{
	PLUS, MINUS, TIMES, DIVIDE, EXPONENT, LPAREN, RPAREN, INTLIT, 
	FLOATLIT, EOLN, EOS
}

enum NonTerminal
{
	PROGRAM, STATEMENT, EXPRESSION, TERM, FACTOR, EXPONENT, NEG_EXPR, NUM, RETN, 
	NONE
}
